spring:
  application:
    name: AdminService
  datasource:
    url: jdbc:mariadb://localhost:3306/mcma
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true