spring:
  application:
    name: Backend
  datasource:
    url: jdbc:mariadb://localhost:3306/mcma
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  web:
    resources:
      add-mappings: true
  devtools:
    add-properties: false
    restart:
      enabled: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org:
      springframework:
        web: DEBUG
    web: debug