spring:
  application:
    name: Backend
  datasource:
    url: jdbc:mariadb://localhost:3306/mcma
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  web:
    resources:
      add-mappings: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html